[project]
name = "BrainSynth"
version = "0.0.1"
description = "Tool for generating synthetic images of the brain and head from segmentations."
maintainers = [
    {name = "Jesper Duemose Nielsen"}
]
requires-python = ">=3.11"
dependencies = [
    "nibabel >= 5.1",
    "numpy >= 1.26",
    "scipy >= 1.11",
    "torch >= 2",
]

[project.optional-dependencies]
generate = [
    "scikit-learn >= 1.3",
    "surfa >= 0.6",
]
