[project]
name = "BrainSynth"
version = "0.0.1"
description = "Tool for generating synthetic brain and head images from segmentations."
maintainers = [
    {name = "Jesper Duemose Nielsen"}
]
requires-python = ">=3.11"
dependencies = [
    "nibabel >= 5.1",
    "numpy >= 1.26",
    "scipy >= 1.11",
    # "scikit-learn >= 1.3",
    # "surfa >= 0.6",
    "torch >= 2",
]
